export const darkTheme = {
    dark: true,
    colors: {
        background: "#282828",
        upper_background: "#444444",
        text: "#ffffff",
        subtitle: "#acacac",
        red: "#EE2929",
        yellow: "#FFBF1C",
        primary: "#7EC13A",
        middle_grey: "#7B7B7B",
        white: "#ffffff",
        flatlist_line: "#EE2929",
        flatlist_transport: "#ffffff",
        linear_gradient_primary: "#444444",
        linear_gradient_secondary: "#282828",
        shadow: "#000000",
        divider: "#444444",
        go_button: "#186FFF",
        my_location: "#5f9cff",
    },
};

export const lightTheme = {
    dark: false,
    colors: {
        background: "#ffffff",
        upper_background: "#ffffff",
        text: "#000",
        subtitle: "#555",
        red: "#EE2929",
        yellow: "#fea621",
        primary: "#7EC13A",
        middle_grey: "#7B7B7B",
        white: "#fff",
        flatlist_line: "#ffffff",
        flatlist_transport: "#EE2929",
        linear_gradient_primary: "#eeeeee",
        linear_gradient_secondary: "#cccccc",
        shadow: "#000000",
        divider: "#e0e0e0",
        go_button: "#186FFF",
        my_location: "#186FFF",
    },
};
